import {launch} from '@gpuix/react/automation'
import {mkdir,mkdtemp} from 'node:fs/promises'
import {resolve,join} from 'node:path'
import assert from 'node:assert/strict'
const root=await mkdtemp('/private/tmp/buddymac-ui-')
const env={...process.env,GPUIX_BACKGROUND:'1',BUDDYMAC_DATA_DIR:join(root,'data'),BUDDYMAC_FOCUS_HOME:join(root,'focus'),BUDDYMAC_SPEECH_DATA_DIR:join(root,'speech'),BUDDYMAC_LINY_HOME:join(root,'liny'),BUDDYMAC_LEGACY_FILES_DIR:join(root,'legacy'),BUDDYMAC_LEGACY_DOCK_MANIFEST:join(root,'no-pack.json')}
await mkdir(env.BUDDYMAC_LEGACY_FILES_DIR,{recursive:true})
await mkdir('evidence',{recursive:true})
const fixture=join(root,'Project notes.txt');await Bun.write(fixture,'BuddyMac UI verification fixture. Originals must stay unchanged.')
const add=Bun.spawn([resolve('dist/native/buddymac-files')],{env,stdin:'pipe',stdout:'pipe',stderr:'pipe'});add.stdin.write(JSON.stringify({action:'add',paths:[fixture]}));add.stdin.end();assert.equal(await add.exited,0)
const packaged=process.env.BUDDYMAC_VERIFY_APP
const app=await launch({command:packaged??process.execPath,args:packaged?[]:['src/app.tsx'],env})
const steps:string[]=[]
const frames=await mkdtemp('/private/tmp/buddymac-frames-')
let recording=true
const captured:{path:string;time:number}[]=[]
const capture=(async()=>{while(recording){const path=join(frames,`${String(captured.length).padStart(5,'0')}.png`);await app.screenshot({path});captured.push({path,time:performance.now()});await Bun.sleep(250)}})()
try{
 await app.getByTestId('file-Project notes.txt').waitFor({timeoutMs:20000});steps.push('Imported fixture appears in GPUix Files')
 await app.getByTestId('files-search').fill('no-match');await app.getByText('No matching files.').waitFor();steps.push('File search filters real shelf')
 await app.getByTestId('files-search').fill('');await app.screenshot({path:resolve('evidence/buddymac-files.png')})
 await app.getByTestId('nav-Focus').click();await app.getByTestId('task-new').waitFor({timeoutMs:15000});await app.getByTestId('task-new').click();await app.getByTestId('task-title').fill('Verify BuddyMac');await app.getByTestId('task-save').click();await app.getByText('Verify BuddyMac').waitFor({timeoutMs:15000});await app.getByTestId('task-search').fill('Verify BuddyMac');const check=Bun.spawn([resolve('dist/buddymac-focus'),'snapshot'],{env,stdout:'pipe',stderr:'pipe'});const saved=await new Response(check.stdout).json();assert.equal(await check.exited,0);assert(saved.tasks.some((task:{title:string})=>task.title==='Verify BuddyMac'));steps.push('Task created through native GPUix input and persisted in SwiftData')
 await app.getByTestId('timer-toggle').click();await app.getByTestId('timer-toggle').getByText('Pause').waitFor();await app.getByTestId('timer-toggle').click();await app.getByTestId('timer-toggle').getByText('Start').waitFor();steps.push('Focus timer starts and pauses')
 await app.screenshot({path:resolve('evidence/buddymac-focus.png')});await app.getByTestId('focus-compact').click();await app.getByTestId('compact-focus').waitFor();await app.screenshot({path:resolve('evidence/buddymac-compact-focus.png')});await app.getByTestId('compact-focus-toggle').click();await app.getByTestId('compact-focus-toggle').getByText('Pause').waitFor();await app.getByTestId('compact-focus-toggle').click();await app.getByTestId('compact-focus-toggle').getByText('Start').waitFor();await app.getByTestId('compact-expand').click();steps.push('Compact Focus starts, pauses and restores full window')
 await app.getByTestId('nav-Write').click();const painted=await app.call('getPaintedText',{});assert(!painted.text.includes('FOCUS'),'Inactive panel must not paint');await app.getByTestId('write-input').fill('A local UI test.');await app.getByTestId('write-output').fill('Editable output.');await app.screenshot({path:resolve('evidence/buddymac-write.png')});steps.push('Write input and output editing verified without provider call')
 await app.getByTestId('write-tab-profiles').click();await app.getByTestId('write-new-profile').waitFor({timeoutMs:15000});await app.getByTestId('write-new-profile').click();await app.getByTestId('write-template-new-profile').waitFor();await app.getByTestId('write-template-new-profile').click();await app.getByTestId('profile-name').waitFor({timeoutMs:15000});await app.getByTestId('profile-name').fill('UI proof');await app.getByTestId('profile-instruction').fill('Keep the meaning.');await app.getByTestId('profile-save').click();await Bun.sleep(800);await app.getByTestId('write-profile-edit-1').click();await app.getByText('UI proof').waitFor({timeoutMs:15000});await app.getByTestId('write-tab-rewrite').click();steps.push('Write profile created and saved through the UI');
 await app.getByTestId('nav-Talk').click();await app.getByTestId('talk-record').waitFor();await app.screenshot({path:resolve('evidence/buddymac-talk.png')});await app.getByTestId('talk-compact').click();await app.getByTestId('compact-talk').waitFor();await app.screenshot({path:resolve('evidence/buddymac-compact-talk.png')});await app.getByTestId('compact-expand').click();steps.push('Compact recorder mounts and expands without recording');steps.push('Talk view mounts native speech status without recording')
 await app.getByTestId('nav-Dock').click();await app.getByText('No icon pack yet. Choose a BuddyDock manifest or make one in New pack.').waitFor({timeoutMs:15000});await app.screenshot({path:resolve('evidence/buddymac-dock.png')});steps.push('Dock handles missing pack without changing icons')
 assert.equal(await Bun.file(fixture).text(),'BuddyMac UI verification fixture. Originals must stay unchanged.')
 await app.getByTestId('nav-Liny').click();await app.getByTestId('liny-input').waitFor();await app.screenshot({path:resolve('evidence/buddymac-liny.png')});
 steps.push('Liny input mounts in the bundled GPUix UI');
 await Bun.write('evidence/ui-verification.json',JSON.stringify({verifiedAt:new Date().toISOString(),executable:packaged??'development',kind:'native GPUix UI with isolated fixture stores',steps,limits:['No provider request, microphone, real file drag, or live icon mutation exercised.']},null,2))
 console.log(JSON.stringify({passed:steps.length,steps}))
}catch(error){console.error('Completed steps:',steps);throw error}finally{recording=false;await capture;await app.close();if(captured.length>1){const list=captured.map((frame,index)=>`file '${frame.path}'\nduration ${((captured[index+1]?.time??frame.time+500)-frame.time)/1000}`).join('\n');await Bun.write(join(frames,'frames.txt'),list+`\nfile '${captured.at(-1)!.path}'\n`);const video=Bun.spawn(['ffmpeg','-y','-loglevel','error','-f','concat','-safe','0','-i',join(frames,'frames.txt'),'-vf','scale=1080:760:force_original_aspect_ratio=decrease,pad=1080:760:(ow-iw)/2:(oh-ih)/2:black,setsar=1','-pix_fmt','yuv420p','-movflags','+faststart',resolve('evidence/buddymac-walkthrough.mp4')],{stdout:'inherit',stderr:'inherit'});assert.equal(await video.exited,0)}}
