import {launchInstalled} from './launch-installed'
import {mkdtemp,mkdir} from 'node:fs/promises'
import {join,resolve} from 'node:path'
import assert from 'node:assert/strict'
const root=await mkdtemp('/private/tmp/buddymac-feature-ui-')
const bin='/Users/francescooddo/Applications/BuddyMac.app/Contents/MacOS'
const env={...process.env,GPUIX_BACKGROUND:'1',LINY_MOCK:'1',BUDDYMAC_DATA_DIR:join(root,'data'),BUDDYMAC_FOCUS_HOME:join(root,'focus'),BUDDYMAC_FOCUS_DISABLE_ALERTS:'1',BUDDYMAC_SPEECH_DATA_DIR:join(root,'speech'),BUDDYMAC_LINY_HOME:join(root,'liny'),BUDDYMAC_LEGACY_FILES_DIR:join(root,'none'),BUDDYMAC_LEGACY_DOCK_MANIFEST:join(root,'pack.json'),BUDDYMAC_DOCK_NO_REFRESH:'1'}
async function helper(name:string,args:string[],input?:unknown){const p=Bun.spawn([join(bin,name),...args],{env,stdin:'pipe',stdout:'pipe',stderr:'pipe'});if(input!==undefined)p.stdin.write(JSON.stringify(input));p.stdin.end();const [out,err,code]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);assert.equal(code,0,err);return JSON.parse(out)}
const draft={title:'Finish fixture',notes:'Synthetic task',projectName:'Verification',tags:['test'],priority:'p1'}
const task=(await helper('buddymac-focus',['task-add'],draft)).tasks[0]
const files=['Alpha.txt','Beta.txt','Gamma.txt'].map(name=>join(root,name));for(const path of files)await Bun.write(path,'Synthetic file transfer content.')
await helper('buddymac-files',[],{action:'add',paths:files})
const target=join(root,'Fixture.app');await mkdir(join(target,'Contents/Resources'),{recursive:true});await Bun.write(join(target,'Contents/Info.plist'),'<plist version="1.0"><dict><key>CFBundleIdentifier</key><string>org.buddytools.fixture</string><key>CFBundlePackageType</key><string>APPL</string></dict></plist>')
const icon='/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/GenericApplicationIcon.icns'
await Bun.write(env.BUDDYMAC_LEGACY_DOCK_MANIFEST,JSON.stringify({version:1,theme:'Verification fixture',icons:[{id:'fixture',name:'Verification target',appPath:target,bundleIdentifier:null,iconPath:icon,styledIconPath:icon}]}))
const app=await launchInstalled(Object.fromEntries(Object.entries(env).filter((entry):entry is [string,string]=>typeof entry[1]==='string')))
const checks:string[]=[]
const frames=await mkdtemp('/private/tmp/buddymac-feature-frames-')
let recording=true
const captured:{path:string,time:number}[]=[]
const capture=(async()=>{while(recording){const path=join(frames,`${String(captured.length).padStart(5,'0')}.png`);await app.screenshot({path});captured.push({path,time:performance.now()});await Bun.sleep(1000)}})()
async function checked(name:string,work:()=>Promise<void>){try{await work()}catch(error){await app.screenshot({path:resolve('evidence/live/feature-ui-failure.png')});await Bun.write('evidence/live/feature-ui-failure.json',JSON.stringify(await app.call('getPaintedText',{}),null,2));throw error}checks.push(name);await Bun.write('evidence/live/feature-ui.json',JSON.stringify({verifiedAt:new Date().toISOString(),executable:join(bin,'BuddyMac'),fixtureRoot:root,checks},null,2));console.log(name)}
try{
 await checked('Files multi-selection and remove preserve source files',async()=>{await app.getByTestId('file-Alpha.txt').waitFor();await app.getByTestId('file-Alpha.txt').click();await app.getByTestId('file-Gamma.txt').click({modifiers:'shift'});await app.getByText('Remove').click();await app.getByText('Drop files here, paste them, or choose Add files.').waitFor();for(const path of files)assert(await Bun.file(path).exists())})
 await checked('Files edge left, pin, delay and normal mode persist',async()=>{await app.getByTestId('files-tab-settings').click();await app.getByTestId('files-edge-left').click();await Bun.sleep(500);await app.getByTestId('files-edge-pin').click();await Bun.sleep(500);await app.getByTestId('files-edge-delay').fill('0.4');await app.getByTestId('files-edge-save-delay').click();await Bun.sleep(250);const settings=await Bun.file(join(root,'data/Files/edge.json')).json();assert.equal(settings.side,'left');assert.equal(settings.pinned,true);assert.equal(settings.holdDelay,0.4);await app.screenshot({path:resolve('evidence/live/files-edge.png')});await app.getByTestId('files-edge-off').click();await app.getByTestId('files-tab-shelf').click();await app.getByTestId('nav-Focus').waitFor()})
 await checked('Focus complete, cancel clear, and confirm clear operate on completed tasks',async()=>{await app.getByTestId('nav-Focus').click();await app.getByTestId(`complete-${task.id}`).waitFor();await app.getByTestId(`complete-${task.id}`).click();await app.getByTestId('task-filter-completed').click();await app.getByTestId('task-clear-completed').waitFor();await app.getByTestId('task-clear-completed').click();await app.getByTestId('task-clear-cancel').waitFor();await app.getByTestId('task-clear-cancel').click();assert.equal((await helper('buddymac-focus',['snapshot'])).tasks.length,1);await app.getByTestId('task-clear-completed').waitFor();await app.getByTestId('task-clear-completed').click();await app.getByTestId('task-clear-confirm').waitFor();await app.getByTestId('task-clear-confirm').click();await app.getByText('No tasks match this view.').waitFor();assert.equal((await helper('buddymac-focus',['snapshot'])).tasks.length,0)})
 await checked('Liny remember and new commands return to editable composer',async()=>{await app.getByTestId('nav-Liny').click();await app.getByTestId('liny-input').fill('/remember synthetic UI verification');await app.getByTestId('liny-send').click();await app.getByTestId('liny-send').waitFor();await app.getByTestId('liny-input').fill('/new');await app.getByTestId('liny-send').click();await app.getByTestId('liny-send').waitFor();await app.getByTestId('liny-input').fill('Synthetic verification response');await app.getByTestId('liny-send').click();let replyVisible=false;for(let i=0;i<40;i++){replyVisible=(await app.call("getPaintedText",{})).text.some(value=>value.includes("[mock] You said:"));if(replyVisible)break;await Bun.sleep(250)}assert(replyVisible);await app.getByTestId('liny-send').waitFor()})
 await checked('Liny thinking selection saves through native controls',async()=>{await app.getByTestId('liny-tab-settings').click();await Bun.sleep(1000);await app.getByTestId('liny-thinking-high').waitFor();await app.getByTestId('liny-thinking-high').click();await Bun.sleep(500);await app.getByTestId('liny-configure').click();for(let i=0;i<40&&!await Bun.file(join(root,'liny/profiles/personal/config.json')).exists();i++)await Bun.sleep(250);assert.equal((await Bun.file(join(root,'liny/profiles/personal/config.json')).json()).thinking,'high');await app.screenshot({path:resolve('evidence/live/liny-settings.png')})})
 await checked('Dock applies fixture artwork and enables managed repair',async()=>{await app.getByTestId('nav-Dock').click();await app.getByText('Verification target').waitFor();await app.getByText('○').click();await app.getByTestId('dock-apply').click();await app.getByText('Applied').waitFor({timeoutMs:20000});await app.getByTestId('dock-keep').click();await app.getByText('Applied · kept applied').waitFor({timeoutMs:30000});await app.screenshot({path:resolve('evidence/live/dock-applied.png')})})
 await checked('Dock stops automatic repair through native controls',async()=>{await app.getByTestId('dock-tab-settings').click();await app.getByTestId('dock-stop-keeping').click();await Bun.sleep(300);await Bun.sleep(500);assert.equal((await Bun.file(join(root,'data/Dock/managed.json')).json()).icons.length,0)})
}finally{recording=false;await capture;await app.close();if(captured.length>1){const list=captured.map((frame,index)=>`file '${frame.path}'\nduration ${Math.min(2,((captured[index+1]?.time??frame.time+500)-frame.time)/1000)}`).join('\n');await Bun.write(join(frames,'frames.txt'),list+`\nfile '${captured.at(-1)!.path}'\n`);const video=Bun.spawn(['ffmpeg','-y','-loglevel','error','-f','concat','-safe','0','-i',join(frames,'frames.txt'),'-vf','scale=1080:760:force_original_aspect_ratio=decrease,pad=1080:760:(ow-iw)/2:(oh-ih)/2:black,setsar=1','-pix_fmt','yuv420p','-movflags','+faststart',resolve('evidence/buddymac-feature-walkthrough.mp4')],{stdout:'inherit',stderr:'inherit'});assert.equal(await video.exited,0)}}
console.log(JSON.stringify({passed:checks.length,checks}))
